ALTER TABLE agent_reflections
    ADD COLUMN embedding_provider_id BIGINT NOT NULL DEFAULT 0 AFTER tags_json,
    ADD COLUMN embedding_model VARCHAR(191) NOT NULL DEFAULT '' AFTER embedding_provider_id,
    ADD COLUMN embedding_dimensions INT NOT NULL DEFAULT 0 AFTER embedding_model,
    ADD INDEX idx_reflection_embedding_profile (owner_id, embedding_provider_id, embedding_model, embedding_dimensions);

CREATE TABLE IF NOT EXISTS context_resource_index_outbox (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    owner_id BIGINT NOT NULL,
    workflow_id BIGINT NOT NULL DEFAULT 0,
    resource_type VARCHAR(32) NOT NULL,
    resource_id VARCHAR(191) NOT NULL,
    operation ENUM('upsert','delete') NOT NULL,
    content_hash CHAR(64) NOT NULL DEFAULT '',
    embedding_provider_id BIGINT NOT NULL DEFAULT 0,
    embedding_model VARCHAR(191) NOT NULL DEFAULT '',
    embedding_dimensions INT NOT NULL DEFAULT 0,
    embedding_profile_hash CHAR(64) NOT NULL DEFAULT '',
    status ENUM('pending','processing','completed','dead_letter') NOT NULL DEFAULT 'pending',
    attempt_count INT NOT NULL DEFAULT 0,
    max_attempts INT NOT NULL DEFAULT 8,
    available_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    locked_by VARCHAR(128) NOT NULL DEFAULT '',
    locked_at DATETIME NULL,
    lease_expires_at DATETIME NULL,
    last_error TEXT NULL,
    completed_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_context_resource_version (owner_id, resource_type, resource_id, content_hash, operation, embedding_profile_hash),
    INDEX idx_context_outbox_claim (status, available_at, lease_expires_at, id),
    INDEX idx_context_outbox_resource (owner_id, resource_type, resource_id),
    INDEX idx_context_outbox_profile (embedding_profile_hash, status, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS conversation_compactions (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    owner_id BIGINT NOT NULL,
    conversation_id BIGINT NOT NULL,
    first_message_id BIGINT NOT NULL DEFAULT 0,
    last_message_id BIGINT NOT NULL DEFAULT 0,
    source_fingerprint CHAR(64) NOT NULL,
    trigger_type ENUM('auto','manual') NOT NULL,
    status ENUM('completed','fallback','failed') NOT NULL,
    summary MEDIUMTEXT NULL,
    prompt_version VARCHAR(64) NOT NULL DEFAULT 'codex-compatible-v1',
    provider_id BIGINT NOT NULL DEFAULT 0,
    model VARCHAR(191) NOT NULL DEFAULT '',
    before_tokens INT NOT NULL DEFAULT 0,
    after_tokens INT NOT NULL DEFAULT 0,
    error_message TEXT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uk_conversation_compaction_source (owner_id, conversation_id, source_fingerprint),
    INDEX idx_conversation_compaction_latest (owner_id, conversation_id, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
