-- Restore the retired legacy memory surfaces exactly as they existed before
-- 000017 (i.e. after 000008 removed memory_write_logs.source_message_id).

CREATE TABLE `agent_reflection_evidence` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `reflection_id` bigint NOT NULL,
  `job_id` bigint DEFAULT NULL,
  `run_id` bigint NOT NULL DEFAULT '0',
  `candidate_hash` char(64) NOT NULL,
  `evidence_json` json DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_reflection_evidence_job_candidate` (`job_id`,`candidate_hash`),
  KEY `idx_reflection_evidence_reflection` (`reflection_id`,`created_at`),
  KEY `idx_reflection_evidence_run` (`run_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `agent_reflection_job_outbox` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `event_id` varchar(191) NOT NULL,
  `job_id` bigint NOT NULL,
  `dispatch_seq` int NOT NULL,
  `event_type` enum('job','dlq') NOT NULL DEFAULT 'job',
  `available_at` datetime NOT NULL,
  `status` enum('pending','publishing','published') NOT NULL DEFAULT 'pending',
  `attempt_count` int NOT NULL DEFAULT '0',
  `locked_by` varchar(128) NOT NULL DEFAULT '',
  `locked_at` datetime DEFAULT NULL,
  `published_at` datetime DEFAULT NULL,
  `last_error` text,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_reflection_outbox_event` (`event_id`),
  UNIQUE KEY `uk_reflection_outbox_dispatch` (`job_id`,`dispatch_seq`,`event_type`),
  KEY `idx_reflection_outbox_pending` (`status`,`available_at`,`id`),
  KEY `idx_reflection_outbox_published` (`published_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `agent_reflection_jobs` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `owner_id` bigint NOT NULL,
  `agent_id` bigint NOT NULL,
  `run_id` bigint NOT NULL,
  `trigger_hash` char(64) NOT NULL,
  `provider_id` bigint NOT NULL DEFAULT '0',
  `model` varchar(128) NOT NULL DEFAULT '',
  `mode` varchar(32) NOT NULL DEFAULT '',
  `task` text NOT NULL,
  `payload_json` json DEFAULT NULL,
  `status` enum('pending','running','completed','failed') NOT NULL DEFAULT 'pending',
  `attempt_count` int NOT NULL DEFAULT '0',
  `max_attempts` int NOT NULL DEFAULT '3',
  `locked_by` varchar(128) NOT NULL DEFAULT '',
  `locked_at` datetime DEFAULT NULL,
  `lock_token` char(32) NOT NULL DEFAULT '',
  `lease_expires_at` datetime DEFAULT NULL,
  `last_heartbeat_at` datetime DEFAULT NULL,
  `dispatch_seq` int NOT NULL DEFAULT '0',
  `retry_at` datetime DEFAULT NULL,
  `error_message` text,
  `failure_type` varchar(32) NOT NULL DEFAULT '',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `completed_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_reflection_job_trigger` (`run_id`,`trigger_hash`),
  KEY `idx_reflection_job_claim` (`status`,`retry_at`,`id`),
  KEY `idx_reflection_job_owner_agent` (`owner_id`,`agent_id`),
  KEY `idx_reflection_job_lease` (`status`,`lease_expires_at`,`retry_at`,`id`),
  KEY `idx_reflection_jobs_agent` (`owner_id`,`agent_id`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `agent_reflection_recall_logs` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `owner_id` bigint NOT NULL,
  `reflection_id` bigint NOT NULL,
  `run_id` bigint NOT NULL,
  `score` double NOT NULL DEFAULT '0',
  `rank` int NOT NULL DEFAULT '0',
  `injected_tokens` int NOT NULL DEFAULT '0',
  `outcome` varchar(64) NOT NULL DEFAULT '',
  `verdict` varchar(32) NOT NULL DEFAULT '',
  `feedback_note` text,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `resolved_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_reflection_recall` (`reflection_id`,`run_id`),
  KEY `idx_reflection_recall_run` (`owner_id`,`run_id`),
  KEY `idx_reflection_recall_effect` (`reflection_id`,`verdict`,`outcome`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `agent_reflections` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `owner_id` bigint NOT NULL,
  `agent_id` bigint NOT NULL DEFAULT '0',
  `source_run_id` bigint NOT NULL DEFAULT '0',
  `supersedes_id` bigint DEFAULT NULL,
  `scope` enum('agent','global') NOT NULL DEFAULT 'agent',
  `kind` enum('error_lesson','important_strategy') NOT NULL,
  `status` enum('candidate','active','validated','disputed','superseded','archived') NOT NULL DEFAULT 'candidate',
  `mode` varchar(32) NOT NULL DEFAULT '',
  `trigger_type` varchar(64) NOT NULL DEFAULT '',
  `task_fingerprint` char(64) NOT NULL DEFAULT '',
  `task_summary` text,
  `root_cause_category` varchar(64) NOT NULL DEFAULT '',
  `root_cause` text,
  `corrective_action` text NOT NULL,
  `lesson` text NOT NULL,
  `applicability` text,
  `evidence_json` json DEFAULT NULL,
  `tags_json` json DEFAULT NULL,
  `embedding_provider_id` bigint NOT NULL DEFAULT '0',
  `embedding_model` varchar(191) NOT NULL DEFAULT '',
  `embedding_dimensions` int NOT NULL DEFAULT '0',
  `importance` double NOT NULL DEFAULT '0.5',
  `confidence` double NOT NULL DEFAULT '0.5',
  `content_hash` char(64) NOT NULL,
  `recall_count` int NOT NULL DEFAULT '0',
  `successful_use_count` int NOT NULL DEFAULT '0',
  `harmful_count` int NOT NULL DEFAULT '0',
  `last_recalled_at` datetime DEFAULT NULL,
  `expires_at` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_owner_agent_content` (`owner_id`,`agent_id`,`content_hash`),
  KEY `idx_reflection_scope` (`owner_id`,`agent_id`,`scope`,`status`),
  KEY `idx_reflection_task` (`owner_id`,`task_fingerprint`),
  KEY `idx_reflection_quality` (`owner_id`,`status`,`importance`,`confidence`),
  KEY `idx_reflection_source_run` (`source_run_id`),
  KEY `idx_reflection_expires` (`expires_at`),
  KEY `idx_reflections_agent_scope` (`owner_id`,`agent_id`,`status`),
  KEY `idx_reflection_embedding_profile` (`owner_id`,`embedding_provider_id`,`embedding_model`,`embedding_dimensions`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `memory_write_logs` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `owner_id` bigint NOT NULL,
  `memory_id` bigint DEFAULT NULL,
  `run_id` bigint DEFAULT NULL,
  `action` varchar(32) NOT NULL,
  `before_json` json DEFAULT NULL,
  `after_json` json DEFAULT NULL,
  `reason` text,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_owner_id` (`owner_id`),
  KEY `idx_run_id` (`run_id`),
  KEY `idx_memory_id` (`memory_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
