CREATE TABLE IF NOT EXISTS agent_run_steps (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    owner_id BIGINT NOT NULL,
    run_id BIGINT NOT NULL,
    node_id VARCHAR(128) NULL,
    step_index INT NOT NULL,
    step_type VARCHAR(32) NOT NULL,
    role VARCHAR(32) NULL,
    content TEXT NULL,
    tool_call_id VARCHAR(128) NULL,
    tool_name VARCHAR(128) NULL,
    arguments_json JSON NULL,
    output_json JSON NULL,
    error_message TEXT NULL,
    token_count INT NOT NULL DEFAULT 0,
    latency_ms INT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_owner_run (owner_id, run_id),
    INDEX idx_run_step (run_id, step_index),
    INDEX idx_step_type (step_type),
    INDEX idx_tool_name (tool_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
