ALTER TABLE workflow_profiles
    ADD COLUMN reflection_policy_json JSON NULL AFTER memory_policy_json;

CREATE TABLE IF NOT EXISTS agent_reflections (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    owner_id BIGINT NOT NULL,
    workflow_id BIGINT NOT NULL,
    node_id VARCHAR(128) NOT NULL DEFAULT '',
    source_run_id BIGINT NOT NULL DEFAULT 0,
    supersedes_id BIGINT NULL,
    scope ENUM('node','workflow','global') NOT NULL DEFAULT 'workflow',
    kind ENUM('error_lesson','important_strategy') NOT NULL,
    status ENUM('candidate','active','validated','disputed','superseded','archived') NOT NULL DEFAULT 'candidate',
    mode VARCHAR(32) NOT NULL DEFAULT '',
    trigger_type VARCHAR(64) NOT NULL DEFAULT '',
    task_fingerprint CHAR(64) NOT NULL DEFAULT '',
    task_summary TEXT NULL,
    root_cause_category VARCHAR(64) NOT NULL DEFAULT '',
    root_cause TEXT NULL,
    corrective_action TEXT NOT NULL,
    lesson TEXT NOT NULL,
    applicability TEXT NULL,
    evidence_json JSON NULL,
    tags_json JSON NULL,
    importance DOUBLE NOT NULL DEFAULT 0.5,
    confidence DOUBLE NOT NULL DEFAULT 0.5,
    content_hash CHAR(64) NOT NULL,
    recall_count INT NOT NULL DEFAULT 0,
    successful_use_count INT NOT NULL DEFAULT 0,
    harmful_count INT NOT NULL DEFAULT 0,
    last_recalled_at DATETIME NULL,
    expires_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    UNIQUE KEY uk_owner_workflow_content (owner_id, workflow_id, content_hash),
    INDEX idx_reflection_scope (owner_id, workflow_id, node_id, status),
    INDEX idx_reflection_task (owner_id, task_fingerprint),
    INDEX idx_reflection_quality (owner_id, status, importance, confidence),
    INDEX idx_reflection_source_run (source_run_id),
    INDEX idx_reflection_expires (expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS agent_reflection_jobs (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    owner_id BIGINT NOT NULL,
    workflow_id BIGINT NOT NULL,
    run_id BIGINT NOT NULL,
    node_id VARCHAR(128) NOT NULL DEFAULT '',
    trigger_hash CHAR(64) NOT NULL,
    provider_id BIGINT NOT NULL DEFAULT 0,
    model VARCHAR(128) NOT NULL DEFAULT '',
    mode VARCHAR(32) NOT NULL DEFAULT '',
    task TEXT NOT NULL,
    payload_json JSON NULL,
    status ENUM('pending','running','completed','failed') NOT NULL DEFAULT 'pending',
    attempt_count INT NOT NULL DEFAULT 0,
    max_attempts INT NOT NULL DEFAULT 3,
    locked_by VARCHAR(128) NOT NULL DEFAULT '',
    locked_at DATETIME NULL,
    retry_at DATETIME NULL,
    error_message TEXT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    completed_at DATETIME NULL,
    UNIQUE KEY uk_reflection_job_trigger (run_id, node_id, trigger_hash),
    INDEX idx_reflection_job_claim (status, retry_at, id),
    INDEX idx_reflection_job_owner (owner_id, workflow_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS agent_reflection_recall_logs (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    owner_id BIGINT NOT NULL,
    reflection_id BIGINT NOT NULL,
    run_id BIGINT NOT NULL,
    node_id VARCHAR(128) NOT NULL DEFAULT '',
    score DOUBLE NOT NULL DEFAULT 0,
    rank INT NOT NULL DEFAULT 0,
    injected_tokens INT NOT NULL DEFAULT 0,
    outcome VARCHAR(64) NOT NULL DEFAULT '',
    verdict VARCHAR(32) NOT NULL DEFAULT '',
    feedback_note TEXT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    resolved_at DATETIME NULL,
    UNIQUE KEY uk_reflection_recall (reflection_id, run_id, node_id),
    INDEX idx_reflection_recall_run (owner_id, run_id),
    INDEX idx_reflection_recall_effect (reflection_id, verdict, outcome)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
