CREATE TABLE IF NOT EXISTS agent_improvement_reviews (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    owner_id BIGINT NOT NULL,
    agent_id BIGINT NOT NULL,
    agent_release_id BIGINT NOT NULL,
    conversation_id BIGINT NOT NULL,
    turn_id BIGINT NOT NULL,
    run_id BIGINT NOT NULL,
    provider_id BIGINT NOT NULL,
    model VARCHAR(255) NOT NULL DEFAULT '',
    status VARCHAR(32) NOT NULL DEFAULT 'pending',
    attempt_count INT NOT NULL DEFAULT 0,
    max_attempts INT NOT NULL DEFAULT 3,
    worker_id VARCHAR(255) NOT NULL DEFAULT '',
    lease_token VARCHAR(64) NOT NULL DEFAULT '',
    lease_expires_at DATETIME NULL,
    last_heartbeat_at DATETIME NULL,
    retry_at DATETIME NULL,
    error_message TEXT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    completed_at DATETIME NULL,
    UNIQUE INDEX uk_agent_review_turn (turn_id),
    INDEX idx_agent_review_claim (status, retry_at, lease_expires_at),
    INDEX idx_agent_review_scope (owner_id, agent_id, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS agent_change_proposals (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    owner_id BIGINT NOT NULL,
    agent_id BIGINT NOT NULL,
    review_id BIGINT NOT NULL,
    turn_id BIGINT NOT NULL,
    run_id BIGINT NOT NULL,
    kind VARCHAR(32) NOT NULL,
    title VARCHAR(512) NOT NULL,
    content MEDIUMTEXT NOT NULL,
    payload_json JSON NOT NULL,
    evidence_json JSON NOT NULL,
    diff_json JSON NOT NULL,
    confidence DOUBLE NOT NULL DEFAULT 0,
    checksum CHAR(64) NOT NULL,
    security_status VARCHAR(32) NOT NULL DEFAULT 'passed',
    security_reason VARCHAR(512) NOT NULL DEFAULT '',
    status VARCHAR(32) NOT NULL DEFAULT 'pending',
    decision_note TEXT NULL,
    decided_by BIGINT NULL,
    decided_at DATETIME NULL,
    applied_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE INDEX uk_agent_proposal_checksum (owner_id, agent_id, kind, checksum),
    INDEX idx_agent_proposal_scope (owner_id, agent_id, status, id),
    INDEX idx_agent_proposal_review (review_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
