CREATE TABLE IF NOT EXISTS app_metadata (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    meta_key VARCHAR(128) NOT NULL UNIQUE,
    meta_value TEXT,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;