ALTER TABLE knowledge_bases
    DROP INDEX idx_rerank_provider_id,
    DROP INDEX idx_embedding_provider_id,
    DROP COLUMN rerank_model,
    DROP COLUMN rerank_provider_id,
    DROP COLUMN rerank_enabled,
    DROP COLUMN hybrid_weight,
    DROP COLUMN embedding_dimensions,
    DROP COLUMN embedding_model,
    DROP COLUMN embedding_provider_id;
