# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from agentcanvas.pythonbridge.v1 import bridge_pb2 as agentcanvas_dot_pythonbridge_dot_v1_dot_bridge__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in agentcanvas/pythonbridge/v1/bridge_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PythonBridgeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/agentcanvas.pythonbridge.v1.PythonBridge/Health',
                request_serializer=agentcanvas_dot_pythonbridge_dot_v1_dot_bridge__pb2.HealthRequest.SerializeToString,
                response_deserializer=agentcanvas_dot_pythonbridge_dot_v1_dot_bridge__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.GetCapabilities = channel.unary_unary(
                '/agentcanvas.pythonbridge.v1.PythonBridge/GetCapabilities',
                request_serializer=agentcanvas_dot_pythonbridge_dot_v1_dot_bridge__pb2.CapabilitiesRequest.SerializeToString,
                response_deserializer=agentcanvas_dot_pythonbridge_dot_v1_dot_bridge__pb2.CapabilitiesResponse.FromString,
                _registered_method=True)
        self.ChunkDocument = channel.unary_unary(
                '/agentcanvas.pythonbridge.v1.PythonBridge/ChunkDocument',
                request_serializer=agentcanvas_dot_pythonbridge_dot_v1_dot_bridge__pb2.ChunkDocumentRequest.SerializeToString,
                response_deserializer=agentcanvas_dot_pythonbridge_dot_v1_dot_bridge__pb2.ChunkDocumentResponse.FromString,
                _registered_method=True)
        self.ListTools = channel.unary_unary(
                '/agentcanvas.pythonbridge.v1.PythonBridge/ListTools',
                request_serializer=agentcanvas_dot_pythonbridge_dot_v1_dot_bridge__pb2.ListToolsRequest.SerializeToString,
                response_deserializer=agentcanvas_dot_pythonbridge_dot_v1_dot_bridge__pb2.ListToolsResponse.FromString,
                _registered_method=True)
        self.ExecuteTool = channel.unary_unary(
                '/agentcanvas.pythonbridge.v1.PythonBridge/ExecuteTool',
                request_serializer=agentcanvas_dot_pythonbridge_dot_v1_dot_bridge__pb2.ExecuteToolRequest.SerializeToString,
                response_deserializer=agentcanvas_dot_pythonbridge_dot_v1_dot_bridge__pb2.ExecuteToolResponse.FromString,
                _registered_method=True)


class PythonBridgeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCapabilities(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChunkDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTools(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteTool(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PythonBridgeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=agentcanvas_dot_pythonbridge_dot_v1_dot_bridge__pb2.HealthRequest.FromString,
                    response_serializer=agentcanvas_dot_pythonbridge_dot_v1_dot_bridge__pb2.HealthResponse.SerializeToString,
            ),
            'GetCapabilities': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCapabilities,
                    request_deserializer=agentcanvas_dot_pythonbridge_dot_v1_dot_bridge__pb2.CapabilitiesRequest.FromString,
                    response_serializer=agentcanvas_dot_pythonbridge_dot_v1_dot_bridge__pb2.CapabilitiesResponse.SerializeToString,
            ),
            'ChunkDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.ChunkDocument,
                    request_deserializer=agentcanvas_dot_pythonbridge_dot_v1_dot_bridge__pb2.ChunkDocumentRequest.FromString,
                    response_serializer=agentcanvas_dot_pythonbridge_dot_v1_dot_bridge__pb2.ChunkDocumentResponse.SerializeToString,
            ),
            'ListTools': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTools,
                    request_deserializer=agentcanvas_dot_pythonbridge_dot_v1_dot_bridge__pb2.ListToolsRequest.FromString,
                    response_serializer=agentcanvas_dot_pythonbridge_dot_v1_dot_bridge__pb2.ListToolsResponse.SerializeToString,
            ),
            'ExecuteTool': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteTool,
                    request_deserializer=agentcanvas_dot_pythonbridge_dot_v1_dot_bridge__pb2.ExecuteToolRequest.FromString,
                    response_serializer=agentcanvas_dot_pythonbridge_dot_v1_dot_bridge__pb2.ExecuteToolResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agentcanvas.pythonbridge.v1.PythonBridge', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agentcanvas.pythonbridge.v1.PythonBridge', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PythonBridge(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentcanvas.pythonbridge.v1.PythonBridge/Health',
            agentcanvas_dot_pythonbridge_dot_v1_dot_bridge__pb2.HealthRequest.SerializeToString,
            agentcanvas_dot_pythonbridge_dot_v1_dot_bridge__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCapabilities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentcanvas.pythonbridge.v1.PythonBridge/GetCapabilities',
            agentcanvas_dot_pythonbridge_dot_v1_dot_bridge__pb2.CapabilitiesRequest.SerializeToString,
            agentcanvas_dot_pythonbridge_dot_v1_dot_bridge__pb2.CapabilitiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChunkDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentcanvas.pythonbridge.v1.PythonBridge/ChunkDocument',
            agentcanvas_dot_pythonbridge_dot_v1_dot_bridge__pb2.ChunkDocumentRequest.SerializeToString,
            agentcanvas_dot_pythonbridge_dot_v1_dot_bridge__pb2.ChunkDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTools(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentcanvas.pythonbridge.v1.PythonBridge/ListTools',
            agentcanvas_dot_pythonbridge_dot_v1_dot_bridge__pb2.ListToolsRequest.SerializeToString,
            agentcanvas_dot_pythonbridge_dot_v1_dot_bridge__pb2.ListToolsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteTool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentcanvas.pythonbridge.v1.PythonBridge/ExecuteTool',
            agentcanvas_dot_pythonbridge_dot_v1_dot_bridge__pb2.ExecuteToolRequest.SerializeToString,
            agentcanvas_dot_pythonbridge_dot_v1_dot_bridge__pb2.ExecuteToolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
